---
-   name: Add Certbot repository
    apt_repository:
        repo: 'deb http://ftp.debian.org/debian buster-backports main'
        state: present
        filename: buster-backports
        update_cache: yes

-   name: Install Certbot
    apt:
        name: certbot
        state: present
        default_release: buster-backports
        update_cache: yes

-   name: Copy Certbot configuration
    copy:
        src: files/cli.ini
        dest: /etc/letsencrypt/cli.ini
        owner: root
        group: root
        mode: 0644

-   name: Remove useless packages
    apt:
        autoclean: yes

-   name: Remove useless dependencies
    apt:
        autoremove: yes
